### ISSUE TITLE
Support for earlier PHP versions

### ISSUE THREAD

**Issue by ScottA38** [bitExpert/phpstan-magento#142]
I recently discovered your module, however I am unable to install due to this error:
![image](https://user-images.githubusercontent.com/32736033/133752835-ccfdefcf-cc0a-452a-b06d-db8aad13a1f0.png)

### Steps

1. Run `composer require --dev bitexpert/phpstan-magento`

## System
- Ubuntu 20.04
- PHP v7.1.33

### Expected Result
1. phpstan-magento installed successfully
2. Entry for phpstan-magento added to composer.json

### Actual Result
1. Install error - see screenshot

### Suggestions/comments

- Please make error message more verbose, perhaps like Magerun2: informing about the minimum version of PHP required to install the module, instead of only that use has incorrect version
- Will there be support for php7.1 at some point? If not can I potentially install the package with a different php version and after it would work with PHP7.1? (maybe custom phpstan config?)

**Comment by shochdoerfer** [comment]
Thanks for opening the issue. Since PHP 7.1 is not actively supported anymore, I don't feel it make sense to use PHP 7.1 as a minimum requirement. Since this might also influence the package versions we can install as dependencies of `bitexpert/phpstan-magento` I would like to avoid the move, I'd rather also deprecate PHP 7.2 & PHP 7.3 in the near future. That depends a bit which minimum Magento versions we would want to support. Which Magento version are you using?

You should be able to install the package with the `--ignore-platform-reqs` flag of Composer. In the latest version you can install the package alongside of your Magento project (e.g. different folder). That means you don't have to use `--ignore-platform-reqs` when interacting with your Magento application (and risk borked dependencies).

**Comment by shochdoerfer** [comment]
By the way, the error message is generated by Composer, not by this package. I don't think there is a way to change that. We can however add the minimum PHP version to the README.md file if that helps.

**Comment by ScottA38** [comment]
Hey, thanks for the helpful reply

> Which Magento version are you using?

Magento version 2.3.1
 
> You should be able to install the package with the `--ignore-platform-reqs` flag of Composer. In the latest version you can install the package alongside of your Magento project (e.g. different folder). That means you don't have to use `--ignore-platform-reqs` when interacting with your Magento application (and risk borked dependencies).

Can you explain a little further please about the separate folder? What kind of configuration is needed to link phpstan-magento to my actual M2 project

> By the way, the error message is generated by Composer, not by this package. I don't think there is a way to change that. We can however add the minimum PHP version to the README.md file if that helps.

I think I would gain benefit from this 🙏 

Also understandable about not supporting PHP versions that are past EOL
As a professional developer I should probably know these things already 😨 😇

**Comment by shochdoerfer** [comment]
My bad, I somehow lost track of this issue.

Assuming you have installed your Magento project in `/some/dir/magento` you could install PHPStan and this extension in `/some/dir`. Make sure to use the `--ignore-platform-reqs` to ignore the minimum PHP version that is required by this extension. Once both Composer dependencies have been installed, create a `phpstan.neon` configuration file in `/some/dir` and configure the path to your app/code folder relative to where the `phpstan.neon` file is located. You would also need to add the vendor directory of your Magento installation to the path as well so that PHPstan can resolve the 3rd party classes used.
