### ISSUE TITLE
Issue when installing latest version

### ISSUE THREAD

**Issue by esteban-serfe** [bitExpert/phpstan-magento#165]
When trying to install version 0.11.0 found issues with already existing installation requirements from Magento packages ( Magento OpenSource 2.4.3 )

```
> composer require --dev  bitexpert/phpstan-magento
Using version ^0.11.0 for bitexpert/phpstan-magento
./composer.json has been updated
Gathering patches for root package.
Loading composer repositories with package information
Warning from https://repo.packagist.org: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2. See https://blog.packagist.com/deprecating-composer-1-support/
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for bitexpert/phpstan-magento ^0.11.0 -> satisfiable by bitexpert/phpstan-magento[v0.11.0].
    - bitexpert/phpstan-magento v0.11.0 requires phpstan/phpstan ^1.1.0 -> satisfiable by phpstan/phpstan[1.1.0, 1.1.1, 1.1.2, 1.2.0, 1.3.x-dev] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.
```
Installing version 0.10.* works.

**Comment by shochdoerfer** [comment]
Thanks for opening your first issue.

This is a known issue and it's stated in the README file that the extension requires PHPStan 1.1. If you are using a Magento version that requires an older version of PHPStan, you need to manually upgrade before installing this extension.

Magento pinned PHPstan to a 0.12 version and PHPStan recently released version 1.0. Since there will be no support for older versions by PHPStan, we had to do this move. The next Magento release will require PHPStan 1.x which should fix this but for now, you have to manually adjust the PHPStan version if you want to use the extension.

Versions 0.10 and 0.11 of this extension are compatible in features, so you don't miss anything when using version 0.10. You could even pin that version in your composer.json. Sadly this will change in the next version 0.12 where we will add support for extension attributes.

**Comment by shochdoerfer** [comment]
Also thanks for giving this extension a try. Would love to hear your feedback!

**Comment by esteban-serfe** [comment]
Hi @shochdoerfer:
Thanks for the feedback. Might be needed to add explanation on the readme for this last change for those who are not familliar with the version mambo is going on with Magento and PHPStan.

I'm starting to review this tool to add to our interanl process and pipelines, so will let you know if there is something we can improve or discuss once we start giving it a spin on all our project.

You can close this issue if you like. I've already pinned the version on the composer file.

Regards
Esteban

**Comment by shochdoerfer** [comment]
I would have thought Composer automatically picks the previous version as it would have matched your constraint. I thought the issue only pops up when upgrading an existing Magento project.
