### ISSUE TITLE
Add support for laminas/laminas-code 4.5 (which is a dependency of Magento 2.4.4)

### ISSUE THREAD

**Issue by hostep** [bitExpert/phpstan-magento#193]
Hi!

Thanks again for this module!

I was trying to prepare a module of mine to test it with Magento 2.4.4 (of which I have bèta access), but due to dependency constraint conflicts this currently does not work.

- `bitexpert/phpstan-magento` version 0.17.0 [relies on](https://github.com/bitExpert/phpstan-magento/blob/v0.17.0/composer.json#L24): `"laminas/laminas-code": "~3.3.0 || ~3.4.1 || ~3.5.1"`
- `magento/framework` version 103.0.4-beta4 [relies on](https://github.com/magento/magento2/blob/f40c40bcc5b517145beeea2a3322fe305c226a4b/lib/internal/Magento/Framework/composer.json#L29):  `"laminas/laminas-code": "~4.5.0"`

I don't know how easy it would be to expand the version constraints in this module to allow for the same constraint as Magento's? Preferably - if possible - without dropping the older versions to allow this module to be installed on older Magento versions as well.

Thanks!

**Comment by shochdoerfer** [comment]
You are welcome. Yes, once Magento 2.4.4 is released, those constraint needs to be added. Hopefully, we won't run into issues, but that needs to be tested. Since I don't have beta access, I can test this once 2.4.4 is GA. I could imaging being some issues due to PHP 8.1 support. The worst case would be to rip out `laminas/laminas-code`.

I don't yet want to add the dependencies as I am not sure what would happen when Composer can't find the dependencies (for the local development install).

What you could do for now, is to make use of inline aliases, see here: https://getcomposer.org/doc/articles/aliases.md#:~:text=It%20is%20rather%20common%20that%20someone%20will%20want,as%20dev-develop)%20dev-%20must%20prefix%20the%20branch%20name.

**Comment by hostep** [comment]
Thanks @shochdoerfer, I was able to get everything running before your last comment and forgot to report back.
So: phpstan (and this extension) ran fine without any problems at first sight, no weird errors or new problems found. I did indeed solve the problem temporarily with this constraint `"laminas/laminas-code": "4.5.1 as 3.5.1"`

So it sounds promising in that the upgrade of `laminas/laminas-code` seems to cause no issues (at least not in my case).

**Comment by shochdoerfer** [comment]
Does your new project make use of extension attributes? I am asking because `laminas/laminas-code` is currently only used in the generators for the extension attribute classes and interfaces.

**Comment by hostep** [comment]
Ah, good to know. Unfortunately no extension attributes are being used.
So okay, this will need some proper testing indeed after Magento 2.4.4 gets released 🙂

**Comment by hostep** [comment]
Friendly reminder now that Magento 2.4.4 has been released in pre-release (should you have access to that program) 🙂

**Comment by shochdoerfer** [comment]
@hostep I have some bad news for you, I will be on holiday for the next 2 weeks ;( Can you prepare a PR for this? Merging and releasing should be possible for me though.

Making sure CI runs with PHP 7.4 & PHP 8 might get ugly due to the committed composer.lock file, I have solved it for some other tooling like this: https://github.com/hivecommerce/magerun2-list-api-endpoints/blob/main/.github/workflows/ci.yml

**Comment by hostep** [comment]
No worries, I wouldn't consider this bad news, a holiday is always good in my opinion 😄 
Let's see where the PR of Brent gets us (once 2.4.4 is released publicly) 🙂

**Comment by shochdoerfer** [comment]
> No worries, I wouldn't consider this bad news, a holiday is always good in my opinion 😄

True, I just realized how eagerly you are waiting for the next release :)

**Comment by shochdoerfer** [comment]
Fixed!

**Comment by shochdoerfer** [comment]
Version v0.20.0 of `bitexpert/phpstan-magento` just got released!
