### ISSUE TITLE
Move stubs out of src/

### ISSUE THREAD

**Issue by szepeviktor** [bitExpert/phpstan-magento#258]
While browsing this project I've found that stubs live in the same directory as source files.
https://github.com/bitExpert/phpstan-magento/tree/master/src/Magento

Would you welcome a PR that moves stub to `stubs/`?

**Comment by szepeviktor** [comment]
I see you call stubs "mock".

**Comment by szepeviktor** [comment]
I think
```neon
parameters:
	stubFiles:
```
could be used instead of a custom solution.

https://github.com/bitExpert/phpstan-magento/blob/91032ba3777bf22df981c959d70f0fdbc391e515/src/bitExpert/PHPStan/Magento/Autoload/MockAutoloader.php#L15-L38

**Comment by shochdoerfer** [comment]
Thanks for opening an issue first to discuss things.

First of all, yes what is called mocks are actually stubs. The reasoning behind this is that I did not want to confuse people (well, mainly me) with the stubs from PHPStan as they behave fundamentally differently and I could not come up with a better name.

It does not make sense to rely on PHPStan's stubs because doing that would mean we have to add half of Magento's codebase to this repo. The "problem" with PHPStan's stubs (at least the last time I looked at it) was, that you have to add any class you import/use as a stub as well. In our approach, the autoloader simply loads a different implementation if it exists. From that perspective, things work as they should for me.

Does it make sense to move the files out of the `src` folder? Maybe. Is it worth it? Probably not.

In an ideal world, the subs/mocks would be located in a separate Composer package that depends on a matching Magento version. Because currently, technically false positives could occur when Magento changes one of the classes that we stored as stub/mock. However, I decided against that approach for now, because it simply is way too much management overhead to create a separate package per Magento version and maintain that. Also, so far no one reported false positives from the stub/mock files we provide. As long as that does not happen, I'll leave things as they are.

**Comment by szepeviktor** [comment]
> you have to add any class you import/use as a stub as well

YES!!

**Comment by szepeviktor** [comment]
> to create a separate package per Magento version and maintain that

@shochdoerfer Would you like me to create and maintain a package - e.g `php-stubs/magento-stub` - and include your mocks?

**Comment by shochdoerfer** [comment]
> @shochdoerfer Would you like me to create and maintain a package - e.g php-stubs/magento-stub - and include your mocks?

I don't see a benefit in that.
