### ISSUE TITLE
Current release version not updated

### ISSUE THREAD

**Issue by BorisovskiP** [bitExpert/phpstan-magento#265]
In https://github.com/bitExpert/phpstan-magento/commit/d3dbb8dbc43b8a7a38c49e18ffe161f469e2a0c3, the requirements for phpstan were updated to `"phpstan/phpstan": "~1.8.2"`, however, in the package version, the old requirements are still present.

A fix would be to release a new version so that the requirements are updated.

**Comment by shochdoerfer** [comment]
See my comment here, currently on purpose https://github.com/bitExpert/phpstan-magento/pull/261#issuecomment-1204888959

You can use the dev-master version if you really want PHPStan 1.8 support. I would love to let Ondrej fix the issue first before creating a new version compatible with 1.8. Otherwise, I will get even more issues with complaints (I think).

**Comment by BorisovskiP** [comment]
Thanks for the quick reply and explanation.

**Comment by shochdoerfer** [comment]
Sorry for this ;( Would have loved to solve the issue earlier but too many things came at once. I am confident that once Ondrej is back from his holiday, we can merge & release this soonish.

**Comment by shochdoerfer** [comment]
Here you go: https://github.com/bitExpert/phpstan-magento/releases/tag/v0.24.0

**Comment by BorisovskiP** [comment]
Thank you.
