### ISSUE TITLE
Releases and Changelog

### ISSUE THREAD

**Issue by sprankhub** [bitExpert/phpstan-magento#28]
Thanks for all your work on making this compatible with the latest version of PHPStan! Much appreciated!

Is there any reason why this package does not have proper versioning? It would be nice to have tagged versions and changelogs for them :)

**Comment by shochdoerfer** [comment]
Of course, there are multiple reasons for that - but I am happy to change my mind :)
- first of all, I feel the package is still in early development and I didn't want to add the overhead of versioning to it too early
- Since I did not want to support too many Magento versions, I felt it is fine for now to only have master that works with the latest version and thus I thought versioning is not needed. What I did not take into account are the frequent PHPStan releases and the (many) changes that those bring with.

Seeing that the package has about 12K downloads via Packagist, I might have to change my mind. What do you think?

**Comment by sprankhub** [comment]
Thanks for your quick feedback!

If you feel that the package is not stable, you can simply use a `0.x` version. Although I use it for quite some time now and it works absolutely fine (maybe there are missing features, but I did not encounter any bugs - hence, I would consider it stable).

Fine if you only want to support the latest Magento version. However, then, versioning makes things easier for people who are still stuck on an older version of Magento.

So I would definitely appreciate a proper versioning and would be happy if you changed your mind regarding this :)

**Comment by shochdoerfer** [comment]
I know, it just felt too much work to do all that when I quickly hacked things together last year :P

If fully get your point and will try to prepare a first release soon.

Do you have any public magento module repo that is using this package? I would love to test the package against real-life projects during the build to see if things break or not. Or do you only on private repos?

**Comment by sprankhub** [comment]
Hmm did you close this on purpose? There is no release yet, so maybe it is worth keeping it open?

**Comment by shochdoerfer** [comment]
Working on it (want to add a few improvements first), stay tuned :) Closed the ticket as the decision was done to do so.

**Comment by shochdoerfer** [comment]
Here you go: https://github.com/bitExpert/phpstan-magento/releases/tag/v0.1.0

**Comment by hostep** [comment]
Thanks @shochdoerfer!

Maybe interesting to know, you can view in Github which other packages make use of this one, see: https://github.com/bitExpert/phpstan-magento/network/dependents
