### ISSUE TITLE
Update dependency to phpstan/phpstan 1.11.x

### ISSUE THREAD

**Issue by dimitriBouteille** [bitExpert/phpstan-magento#319]
Please support [phpstan/phpstan](https://github.com/phpstan/phpstan/releases/tag/1.11.1) `1.11.x`

https://github.com/bitExpert/phpstan-magento/pull/318

**Comment by shochdoerfer** [comment]
Thanks for opening your first issue in this repo. And thanks for caring about PHPStan 1.11 :)

I have it on my radar, but I need to find the time to test things in detail. This will take a few more weeks since I am currently quite busy with other stuff. If you are able to test it and report back, that would be super helpful.

**Comment by hostep** [comment]
Some quick feedback from me.

I've tested phpstan 1.11.3 in combination with this module (hacked it using `"phpstan/phpstan": "1.11.3 as 1.10.67"` in composer). Tried it on 4 different Magento modules and no issues found.

But I'm probably not using every single feature this module offers, so can't say for certain if it's fully compatible.

**Comment by shochdoerfer** [comment]
Sounds good, thx Pieter! Will check my schedule to find a slot soonish to prepare the next release. I don't expect anything to break, but we have had issues in the past... :)

**Comment by shochdoerfer** [comment]
Here we go https://github.com/bitExpert/phpstan-magento/releases/tag/v0.31.0

Sorry that it took way longer than expected, too much stuff going on currently. If anyone wants to step up and help as a co-maintainer, let me know. Happy to have more people to take care of this extension.
